#!/usr/bin/env php
<?php
var_dump( ini_get('register_argc_argv') ) ;
var_dump( ini_set('register_argc_argv',1) ) ;
var_dump( ini_get('register_argc_argv') ) ;
die;

require_once(dirname(__FILE__).'/yiic.php');
